// AUTO-GENERATED by packages/tokens/build.mjs — DO NOT EDIT BY HAND.
// Resolved hex for the shadcn semantic tokens, for IMPERATIVE use where a className token can't go:
// react-native-svg fills, ActivityIndicator color, inline styles. Same source as global.css :root,
// so these match bg-primary / text-foreground / … exactly. Regenerate: node packages/tokens/build.mjs
export const tokenColors = {
  background: '#f4f6f4',
  foreground: '#181918',
  card: '#feffff',
  cardForeground: '#181918',
  popover: '#feffff',
  popoverForeground: '#181918',
  primary: '#28d75d',
  primaryForeground: '#0a0b0a',
  secondary: '#eef0ee',
  secondaryForeground: '#181918',
  muted: '#e9ebe9',
  mutedForeground: '#707370',
  accent: '#e9ebe9',
  accentForeground: '#181918',
  destructive: '#fe3266',
  destructiveForeground: '#fcfcfc',
  border: '#dddedd',
  input: '#dddedd',
  ring: '#28d75d',
  success: '#62c43b',
  successForeground: '#171917',
  warning: '#ff9c3c',
  warningForeground: '#1a1816',
} as const
