// AUTO-GENERATED by tools/baseline-capture (Phase 6). Static require map of the Canvas2D baseline
// captures (the parity oracle) so Metro bundles them and RN-Skia can decode each via Skia.Data.fromURI.
// Regenerate after changing docs/baseline/captures: re-copy the PNGs and re-run the generator.
/* eslint-disable @typescript-eslint/no-var-requires */
export const CAPTURES: Record<string, number> = {
  "brush-blending-over-coral": require("../../assets/golden/captures/brush-blending-over-coral.png"),
  "brush-buildup-overstroke": require("../../assets/golden/captures/brush-buildup-overstroke.png"),
  "brush-default-scurve-ramp": require("../../assets/golden/captures/brush-default-scurve-ramp.png"),
  "brush-texture-canvas-hswipe": require("../../assets/golden/captures/brush-texture-canvas-hswipe.png"),
  "brush-wet-hswipe-high": require("../../assets/golden/captures/brush-wet-hswipe-high.png"),
  "drybrush-dryness-high-diag": require("../../assets/golden/captures/drybrush-dryness-high-diag.png"),
  "drybrush-dryness-low-diag": require("../../assets/golden/captures/drybrush-dryness-low-diag.png"),
  "eraser-soft-over-fill": require("../../assets/golden/captures/eraser-soft-over-fill.png"),
  "inkbrush-default-scurve-high": require("../../assets/golden/captures/inkbrush-default-scurve-high.png"),
  "marker-hswipe-med": require("../../assets/golden/captures/marker-hswipe-med.png"),
  "marker-overlap-cross": require("../../assets/golden/captures/marker-overlap-cross.png"),
  "pen-hswipe-med": require("../../assets/golden/captures/pen-hswipe-med.png"),
  "pen-scurve-ramp": require("../../assets/golden/captures/pen-scurve-ramp.png"),
  "pencil-hswipe-high": require("../../assets/golden/captures/pencil-hswipe-high.png"),
  "pencil-hswipe-low": require("../../assets/golden/captures/pencil-hswipe-low.png"),
  "pencil-hswipe-med": require("../../assets/golden/captures/pencil-hswipe-med.png"),
  "smudge-across-boundary": require("../../assets/golden/captures/smudge-across-boundary.png"),
  "spray-density-high-hswipe": require("../../assets/golden/captures/spray-density-high-hswipe.png"),
  "spray-density-low-hswipe": require("../../assets/golden/captures/spray-density-low-hswipe.png"),
  "watercolor-dwell-pool": require("../../assets/golden/captures/watercolor-dwell-pool.png"),
  "watercolor-scurve-med": require("../../assets/golden/captures/watercolor-scurve-med.png"),
  "waterdrop-ink-over-fill": require("../../assets/golden/captures/waterdrop-ink-over-fill.png"),
  "waterdrop-water-only-over-fill": require("../../assets/golden/captures/waterdrop-water-only-over-fill.png"),
}
