#!/usr/bin/env node
// Token generator — single source (tokens.json, canonical = web brand palette) -> native global.css.
// Zero dependencies: implements OKLCH -> OKLab -> linear sRGB -> sRGB -> HSL (Björn Ottosson's matrices),
// so the web's OKLCH brand colors are emitted as native shadcn HSL channels. This converges native to
// the web palette WITHOUT touching the prod web CSS (web stays OKLCH + remains the reference).
//
//   node packages/tokens/build.mjs            # writes apps/native/global.css + prints the table
//   node packages/tokens/build.mjs --out /tmp/x.css   # dry-run to another path (inspect first)
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const outArg = process.argv.indexOf('--out')
const OUT = outArg !== -1 ? resolve(process.argv[outArg + 1]) : resolve(HERE, '../../apps/native/global.css')
// Resolved hex per token, for imperative (non-className) use: RN-SVG fills, ActivityIndicator,
// inline styles. Skipped when doing a --out dry-run.
const TS_OUT = outArg !== -1 ? null : resolve(HERE, '../../apps/native/src/theme/tokenColors.ts')
const camel = (s) => s.replace(/-([a-z])/g, (_, c) => c.toUpperCase())

// ── OKLCH string -> {L(0..1), C, H(deg)} ──────────────────────────────────────
function parseOklch(str) {
  const m = /oklch\(\s*([^)]+)\)/i.exec(str)
  if (!m) throw new Error(`not an oklch() value: ${str}`)
  const parts = m[1].trim().split('/')[0].trim().split(/\s+/)
  const num = (t) => (t.endsWith('%') ? parseFloat(t) / 100 : parseFloat(t))
  const L = num(parts[0])
  const C = parseFloat(parts[1] ?? '0')
  const H = parseFloat(parts[2] ?? '0') || 0
  return { L, C, H }
}

// ── OKLCH -> sRGB (0..1), Ottosson ────────────────────────────────────────────
function oklchToRgb({ L, C, H }) {
  const hr = (H * Math.PI) / 180
  const a = C * Math.cos(hr)
  const b = C * Math.sin(hr)
  const l_ = L + 0.3963377774 * a + 0.2158037573 * b
  const m_ = L - 0.1055613458 * a - 0.0638541728 * b
  const s_ = L - 0.0894841775 * a - 1.291485548 * b
  const l = l_ ** 3, m = m_ ** 3, s = s_ ** 3
  const lin = [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ]
  const g = (x) => {
    x = Math.min(1, Math.max(0, x))
    return x <= 0.0031308 ? 12.92 * x : 1.055 * x ** (1 / 2.4) - 0.055
  }
  return lin.map(g)
}

// ── sRGB (0..1) -> HSL ────────────────────────────────────────────────────────
function rgbToHsl([r, g, b]) {
  const max = Math.max(r, g, b), min = Math.min(r, g, b), d = max - min
  const l = (max + min) / 2
  let h = 0, s = 0
  if (d !== 0) {
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min)
    if (max === r) h = (g - b) / d + (g < b ? 6 : 0)
    else if (max === g) h = (b - r) / d + 2
    else h = (r - g) / d + 4
    h *= 60
  }
  return { h, s: s * 100, l: l * 100 }
}
const toHex = ([r, g, b]) => '#' + [r, g, b].map((x) => Math.round(x * 255).toString(16).padStart(2, '0')).join('')
const hslChannels = ({ h, s, l }) => `${Math.round(h)} ${Math.round(s)}% ${Math.round(l)}%`

// ── build ─────────────────────────────────────────────────────────────────────
const tokens = JSON.parse(readFileSync(resolve(HERE, 'tokens.json'), 'utf8'))
const rows = []
const lines = []
const tsEntries = []
for (const [name, def] of Object.entries(tokens.color)) {
  const oklch = parseOklch(def.oklch)
  const rgb = oklchToRgb(oklch)
  const hsl = rgbToHsl(rgb)
  const channels = hslChannels(hsl)
  const hex = toHex(rgb)
  lines.push(`  --${name}: ${channels};`)
  tsEntries.push(`  ${camel(name)}: '${hex}',`)
  rows.push({ token: name, oklch: def.oklch, hsl: channels, hex })
}
const radius = tokens.radius?.DEFAULT?.value
if (radius) lines.push(`  --radius: ${radius};`)

const css = `@tailwind base;
@tailwind components;
@tailwind utilities;

/* ─────────────────────────────────────────────────────────────────────────────
 * AUTO-GENERATED by packages/tokens/build.mjs — DO NOT EDIT BY HAND.
 * Source of truth: packages/tokens/tokens.json (canonical = the WEB brand palette).
 * Regenerate after editing tokens.json:  node packages/tokens/build.mjs
 *
 * shadcn-convention HSL channels (H S% L%), composed via hsl(var(--token)/<alpha>)
 * in tailwind.config.js. Each value is the web's OKLCH brand color converted to HSL,
 * so bg-primary / text-foreground / … resolve to the SAME color on web and native.
 * ───────────────────────────────────────────────────────────────────────────── */
:root {
${lines.join('\n')}
}
`

writeFileSync(OUT, css)

if (TS_OUT) {
  const ts = `// AUTO-GENERATED by packages/tokens/build.mjs — DO NOT EDIT BY HAND.
// Resolved hex for the shadcn semantic tokens, for IMPERATIVE use where a className token can't go:
// react-native-svg fills, ActivityIndicator color, inline styles. Same source as global.css :root,
// so these match bg-primary / text-foreground / … exactly. Regenerate: node packages/tokens/build.mjs
export const tokenColors = {
${tsEntries.join('\n')}
} as const
`
  writeFileSync(TS_OUT, ts)
}

console.table(rows)
console.log(`\n✓ wrote ${OUT}  (${rows.length} color tokens${radius ? ' + radius' : ''})`)
if (TS_OUT) console.log(`✓ wrote ${TS_OUT}`)
